name = "espress"
uuid = "34b7f61b-799e-4aa8-84dc-ccd4e2e94c3d"
authors = ["edwloef <75493688+edwloef@users.noreply.github.com>"]
version = "0.0.1"

[deps]
Decimals = "abce61dc-4473-55a0-ba07-351d65e31d42"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"

[compat]
Decimals = "0.5.0"
Match = "2.3.0"
